INSERT INTO USER_ (NAME, CITY, STATE, ZIPCODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY)
VALUES ('MOISES', 'GUADALAJARA','JALISCO', 44380, 0, 0, 0);
INSERT INTO USER_ (NAME, CITY, STATE, ZIPCODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY)
VALUES ('ALICIA', 'GUADALAJARA','JALISCO', 44280, 0, 1, 1);
INSERT INTO USER_ (NAME, CITY, STATE, ZIPCODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY)
VALUES ('JAVIER', 'TLAQUEPAQUE','JALISCO', 11111, 0, 0, 0);
INSERT INTO USER_ (NAME, CITY, STATE, ZIPCODE, PEANUT_ALLERGY, EGG_ALLERGY, DAIRY_ALLERGY)
VALUES ('EDGAR', 'TONALA','JALISCO', 22222, 0, 1 ,1);
